package org.example.authservice.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents a user in the authentication system.
 * This entity is mapped to the "users" table in the database.
 * It uses JPA for persistence and Lombok for automatic generation of getters and setters.
 *
 */

@Getter @Setter @Entity
@Table(name = "users")
public class User {

    /**
     * Unique identifier for the user.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user's email address.
     */
    @Getter
    private String email;

    /**
     * The user's password.
     */
    @Getter
    private String password;
}
